-- V1__create_tables.sql

CREATE TABLE users (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             VARCHAR(20)  NOT NULL,
    password_hash        VARCHAR(100) NOT NULL,
    last_opened_board_id BIGINT,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_username CHECK (username ~ '^[A-Za-z0-9_]{4,20}$')
);

CREATE TABLE boards (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    name       VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_boards_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_boards_name CHECK (btrim(name) <> '')
);

CREATE TABLE lists (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id   BIGINT      NOT NULL,
    name       VARCHAR(50) NOT NULL,
    position   INTEGER     NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_lists_board FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE CASCADE,
    CONSTRAINT ck_lists_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_lists_position CHECK (position >= 0),
    CONSTRAINT uq_lists_board_position UNIQUE (board_id, position) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE cards (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id     BIGINT         NOT NULL,
    title       VARCHAR(100)   NOT NULL,
    description VARCHAR(2000),
    due_date    DATE,
    is_done     BOOLEAN        NOT NULL DEFAULT false,
    position    INTEGER        NOT NULL,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT fk_cards_list FOREIGN KEY (list_id) REFERENCES lists (id) ON DELETE CASCADE,
    CONSTRAINT ck_cards_title CHECK (btrim(title) <> ''),
    CONSTRAINT ck_cards_position CHECK (position >= 0),
    CONSTRAINT uq_cards_list_position UNIQUE (list_id, position) DEFERRABLE INITIALLY DEFERRED
);

-- users → boards は循環参照になるため、boards 作成後に追加する
ALTER TABLE users
    ADD CONSTRAINT fk_users_last_opened_board
    FOREIGN KEY (last_opened_board_id) REFERENCES boards (id) ON DELETE SET NULL;

-- インデックス
CREATE INDEX idx_boards_user_created ON boards (user_id, created_at DESC);
CREATE INDEX idx_lists_board         ON lists (board_id);
CREATE INDEX idx_cards_list          ON cards (list_id);

CREATE INDEX idx_boards_deleted ON boards (user_id, deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_lists_deleted  ON lists (board_id, deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_cards_deleted  ON cards (list_id, deleted_at)  WHERE deleted_at IS NOT NULL;
